spring:
  datasource:
    url: jdbc:mysql://database-1.cdmithirw8jv.ap-south-1.rds.amazonaws.com:3306/emdb
    username: admin
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect